"""Remove resources table

Revision ID: 4b3d589b1bda
Revises: 9c772ee0c861
Create Date: 2025-08-07 22:14:38.674951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4b3d589b1bda'
down_revision: Union[str, Sequence[str], None] = '9c772ee0c861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('item'), table_name='resources')
    op.drop_index(op.f('ix_resources_amount'), table_name='resources')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_constraint(op.f('recipes_ibfk_2'), 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'resource_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('resource_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('recipes_ibfk_2'), 'recipes', 'resources', ['resource_id'], ['id'])
    op.create_table('resources',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('amount', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_index(op.f('ix_resources_amount'), 'resources', ['amount'], unique=False)
    op.create_index(op.f('item'), 'resources', ['item'], unique=True)
    # ### end Alembic commands ###
