"""Sync schema

Revision ID: 9c772ee0c861
Revises: 
Create Date: 2025-08-07 17:38:17.552541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9c772ee0c861'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_details', sa.Column('quantity', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_order_details_amount'), table_name='order_details')
    op.create_index(op.f('ix_order_details_quantity'), 'order_details', ['quantity'], unique=False)
    op.drop_column('order_details', 'amount')
    op.alter_column('orders', 'customer_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('orders', 'total_price',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('orders', 'tracking_number',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('orders', 'promo_code',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_unique_constraint(None, 'orders', ['tracking_number'])
    op.create_foreign_key(None, 'recipes', 'ingredients', ['ingredient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='unique')
    op.alter_column('orders', 'promo_code',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('orders', 'tracking_number',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('orders', 'total_price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('orders', 'customer_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.add_column('order_details', sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_order_details_quantity'), table_name='order_details')
    op.create_index(op.f('ix_order_details_amount'), 'order_details', ['amount'], unique=False)
    op.drop_column('order_details', 'quantity')
    # ### end Alembic commands ###
